import Head from 'next/head'
import BlogCard from '../componets/BlogCard'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request';
const hygraph = new GraphQLClient("https://api-us-east-1.hygraph.com/v2/cl67vdvmecoq401uk6jz4enuq/master")
const QUERY =gql`
{
  posts {
    id
    title
    datePublished
    slug
    content {
      html
    }
    author {
      name
      avatar {
        url
      }
    }
    coverPhoto {
      publishedAt
      createdBy {
        id
      }
      url
    }
  }
}
`; 

export async function getStaticProps() {

  const { posts } = await hygraph.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            title={post.title}

            author={post.author}

            coverPhoto={post.coverPhoto}

            key={post.key}

            datePublished={post.datePublished}


            slug={post.slug}
          />
        ))}
      </main>

    </div>
  );
}
